src/services/account/routes/project.py
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from src.services.account import Project
from src.services.account.forms import ProjectForm


project_bp = Blueprint("project_bp", __name__, url_prefix="/project/~/")


@project_bp.route("/add/", methods=["GET", "POST"])
@login_required
def create_project():
    page_title = "Saisir des mots-clés/phrases-clés"

    form = ProjectForm()
    if form.validate_on_submit():
        keywords = form.name.data.split(",")
        for key in keywords:
            project = Project(name=key.strip(), user=current_user._get_current_object())
            project.save()
        return redirect(url_for("dashboard_bp.dashboard"))
    return render_template("project/create.html", form=form, page_title=page_title)

src/services/dashboard/routes.py
from flask import abort
from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from src.services.account import Project
from src.services.account import utils
from src.services.account.forms import ProjectForm

from .func_utils import Hashtags, Comments


dashboard_bp = Blueprint("dashboard_bp", __name__, url_prefix="/panel/~/")


@dashboard_bp.before_request
def dashboard_before_request():
    g.hashtag = Hashtags(current_user)
    g.hashtags_data = g.hashtag.get_hashtag_data()

    g.comment = Comments(current_user)
    g.comments_data = g.comment.get_comments_data()


@dashboard_bp.get("/dashboard/")
@login_required
def dashboard():
    page_title = "Tableau de bord"

    print("hashtags -->", g.hashtags_data)
    print("comments -->", g.comments_data)

    return render_template(
        "dashboard/_base.html",
        user=current_user,
        hashtags=g.hashtags_data,
        page_title=page_title,
    )


@dashboard_bp.get("/project/")
@login_required
def get_projects():
    page_title = "projets"

    # stats_data = ""
    # data = Hashtags(current_user)
    # for item in Project.all(current_user):
    #     stats_data = data.get_statistic(item.name)

    return render_template(
        "project/list.html",
        user=current_user,
        page_title=page_title.capitalize(),
        # stat=stats_data,
    )


@dashboard_bp.get("/result/<string:public_id>")
@login_required
def detail_project(public_id: str):
    project = utils.abort_if_project_doesnt_exist(public_id)

    page_name = project.name
    page_title = "Tag '{0}' data".format(page_name)

    # items_data = g.data.get_detail(page_name)

    return render_template(
        "project/detail.html",
        project=project,
        user=current_user,
        page_title=page_title,
        # item=items_data,
        # stat=g.stats_data,
        # stat_fb=g.stat_fb,
        # stat_insta=g.stat_insta,
    )


@dashboard_bp.get("/result/fb/<string:public_id>")
@login_required
def facebook_detail_project(public_id: str):
    project = utils.abort_if_project_doesnt_exist(public_id)

    page_title = f"Facebook data : '{project.name}!r'"

    # data = Hashtags(current_user)
    # items_data = data.get_detail(project.name)
    # stats_data = data.get_statistic(project.name)

    return render_template(
        "project/fb.html",
        project=project,
        user=current_user,
        page_title=page_title,
        # item=items_data,
        # stat=stats_data,
    )


@dashboard_bp.get("/result/in/<string:public_id>")
@login_required
def instagram_detail_project(public_id: str):
    project = utils.abort_if_project_doesnt_exist(public_id)

    page_title = "Instagram data : '{0}'".format(project.name)

    data = Hashtags(current_user)
    # items_data = data.hashtags_data(project.name)

    return render_template(
        "project/fb.html",
        project=project,
        user=current_user,
        page_title=page_title,
        # item=items_data,
    )


@dashboard_bp.route("/update/<string:public_id>", methods=["GET", "POST"])
@login_required
def update_project(public_id: str):
    page_title = "Mettre à jour les mots-clés/phrases-clés"
    project = utils.abort_if_project_doesnt_exist(public_id)

    if project.user_id != current_user.public_id:
        abort(403)

    form = ProjectForm()
    if form.validate_on_submit():
        keywords = form.name.data.split(",")
        name_data = keywords[0].strip()
        Project.update(project, name_data)
        return redirect(url_for("dashboard_bp.dashboard"))
    return render_template(
        "project/update.html", form=form, page_title=page_title, project=project
    )


@dashboard_bp.get("/delete/<string:public_id>/")
@login_required
def delete_project(public_id: str):
    project = utils.abort_if_project_doesnt_exist(public_id)
    if project.user_id != current_user.public_id:
        abort(403)
    flash(f"{project.name} supprimé avec succès !", "success")
    project.remove()
    return redirect(url_for("dashboard_bp.get_projects"))

src/templates/project/create.html
{% extends "account/_base.html" %}

{% block account_header %}
    <div class="text-center mt-4">
        <h1 class="h2">{{ page_title }}</h1>
        <p class="lead">
            Tapez les phrases séparées par des virgules à surveiller.
        </p>
    </div>
{% endblock account_header %}

{% block account_body %}
    <form action="." method="POST">

        {{ form.hidden_tag() }}
        {{ form.csrf_token }}

        <div class="mb-3">
            {{ form.name.label(class="form-label mb-2") }}
            {{ form.name(class="form-control form-control-lg shadow-none", placeholder='Ex: carein') }}
        </div>

        {% if form.name.errors %}
            <div class="invalid-feedback">
                {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}

        <div class="d-grid gap-2 mt-3">
            {{ form.submit(class="btn btn-lg btn-primary") }}
        </div>
    </form>
{% endblock account_body %}

src/templates/project/detail.html
{% extends "dashboard/_base.html" %}

{% block body_content_dashboard %}
	<div class="row">
		{% include "dashboard/paths/_kpi.html" %}
	</div>
	<div class="row">
		<div class="col-md-8">
			{% for item in item %}
				{% include "dashboard/paths/_data.html" %}
			{% endfor %}
		</div>
		<div class="col-md-4">
			<div class="card flex-fill">
				<div class="card-body">
					<h3>Facebook data</h3>
					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="heart"></i> Likes</strong>
							<h2 class="text-muted">{{ stat_fb[0] }}</h2>
						</div>
					</div>

					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="repeat"></i> Commentaires</strong>
							<h2 class="text-muted">{{ stat_fb[1] }}</h2>
						</div>
					</div>

					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="share-2"></i> Partages</strong>
							<h2 class="text-muted">{{ stat_fb[2] }}</h2>
						</div>
					</div>

					<div class="d-grid">
						<a href="{{ url_for('dashboard_bp.facebook_detail_project', public_id=project.public_id) }}" type="button" class="btn btn-primary mb-3 text-uppercase">
							donnée facebook uniquement
						</a>
					</div>
				</div>
			</div>

			<div class="card flex-fill">
				<div class="card-body">
					<h3>Instagram data</h3>

					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="heart"></i> Likes</strong>
							<h2 class="text-muted">{{ stat_insta[0] }}</h2>
						</div>
					</div>

					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="repeat"></i> Commentaires</strong>
							<h2 class="text-muted">{{ stat_insta[1] }}</h2>
						</div>
					</div>

					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="share-2"></i> Partages</strong>
							<h2 class="text-muted">{{ stat_insta[2] }}</h2>
						</div>
					</div>

					<div class="d-grid">
						<a href="{{ url_for('dashboard_bp.instagram_detail_project', public_id=project.public_id) }}" type="button" class="btn btn-primary mb-3 text-uppercase">
							donnée instagram uniquement
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock body_content_dashboard %}

src/templates/project/fb.html
{% extends "dashboard/_base.html" %}

{% block body_content_dashboard %}
	<div class="row">
		{% include "dashboard/paths/_kpi.html" %}
	</div>
	<div class="row">
		<div class="col-md-8">
			{% for item in item %}
				{% include "dashboard/paths/_data.html" %}
			{% endfor %}
		</div>
		<div class="col-md-4">
			<div class="card flex-fill">
				<div class="card-body">
					<h3>{{ page_title }}</h3>
					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="heart"></i> Likes</strong>
							<h2 class="text-muted">{{ stat[0] }}</h2>
						</div>
					</div>

					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="repeat"></i> Commentaires</strong>
							<h2 class="text-muted">{{ stat[1] }}</h2>
						</div>
					</div>

					<div class="d-flex mb-3">
						<div class="flex-grow-1">
							<strong><i class="align-middle me-1 mb-1" data-feather="share-2"></i> Partages</strong>
							<h2 class="text-muted">{{ stat[2] }}</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock body_content_dashboard %}

src/templates/project/list.html
{% extends "dashboard/_base.html" %}

{% block bady_header_top %}
{% endblock bady_header_top %}

{% block body_content_dashboard %}

	{% include "partials/message.html" %}

	<div class="row">
		<div class="col-xl-8">
			<div class="card">
				<div class="card-header pb-0">
					<div class="card-actions float-end">
						<div class="col-auto ms-auto text-end mt-n1">
							<a href="{{ url_for('project_bp.create_project') }}" class="btn btn-danger text-white">
								<i data-feather="plus"></i> Nouveau projet
							</a>
						</div>
					</div>
					<h5 class="card-title mb-0">
						Projets
					</h5>
					<span class="small text-muted py-1">Sélectionner un projet et parcourir les mentions</span>
				</div>

				<div class="card-body">
					<table class="table table-responsive table-striped">
						<thead>
							<tr>
								<th>#</th>
								<th>Projet</th>
								<th>Like</th>
								<th>Commentaire</th>
								<th>Partage</th>
								<th>Date de crétaion</th>
								<th>Paramètres</th>
							</tr>
						</thead>
						<tbody>
							{% for item in user.user_project %}
								<tr>
									<td class="dtr-content" tabindex="0">
										{{ item.id }}
									</td>

									<td>
										<a href="{{ url_for('dashboard_bp.detail_project', public_id=item.public_id) }}">{{ item.name | capitalize() }}</a>
									</td>

									<td>
										{{ stat[0] }}
									</td>

									<td>
										{{ stat[1] }}
									</td>

									<td>
										{{ stat[2] }}
									</td>

									<td>
										{{ moment(item.created_at).format('LL') }}
									</td>

									<td>
										<a href="{{ url_for('dashboard_bp.update_project', public_id=item.public_id) }}" class="btn btn-primary btn-sm">
											<i class="me-1" data-feather="edit-3"></i>
										</a>
										<a type="submit" class="btn btn-danger btn-sm" href="{{ url_for('dashboard_bp.delete_project', public_id=item.public_id) }}">
											<i class="me-1" data-feather="trash-2"></i>
				                        </form>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
{% endblock body_content_dashboard %}

src/templates/project/read.html
{% extends "dashboard/index.html" %}

{% block body_content_dashboar %}
				    
{% endblock body_content_dashboar %}