src/services/account/routes/auth.py
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import session
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user
from src.services.account import User
from src.services.account.forms import LoginForm
from src.services.account.forms import SignupForm


auth_bp = Blueprint("auth_bp", __name__, url_prefix="/auth/")


@auth_bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.ping()


@auth_bp.route("/login/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard_bp.dashboard"))

    form = LoginForm(request.form)
    if form.validate_on_submit():
        addr_email = form.addr_email.data
        user = User.find_by_email(addr_email)
        if user and user.is_active and user.check_password(form.password.data):
            login_user(user, form.remember_me.data)
            next_page = request.args.get("next")
            if next_page is None or not next_page.startswith("/"):
                next_page = url_for("dashboard_bp.dashboard")
            return redirect(next_page)
        else:
            if not user.is_active:
                error_message = "L'utilisateur n'existe pas ou le compte a\
                    été désactivé ! Veuillez contacter l'administrateur système."
            if not user.check_password(form.password.data):
                error_message = "Le mot de passe invalide."

            flash(error_message, category="danger")

    page_title = "Se connecter"
    return render_template("account/login.html", page_title=page_title, form=form)


@auth_bp.route("/register-account/", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated and current_user.is_active:
        flash("Vous êtes déjà inscrit(e).", category="info")
        return redirect(url_for("dashboard_bp.dashboard"))

    form = SignupForm()
    if form.validate_on_submit():
        user_to_create = User(addr_email=form.addr_email.data.lower())
        user_to_create.set_password(form.password.data)
        user_to_create.save()
        msg_success = f"""
            Hey {user_to_create.addr_email},
            votre compte a été créé ! Connectez-vous maintenant !
        """
        flash(msg_success, category="success")
        login_user(user_to_create)
        return redirect(url_for("project_bp.create_project"))
    page_title = "Créer votre compte"
    return render_template("account/signup.html", form=form, page_title=page_title)


@auth_bp.get("/logout/")
@login_required
def logout():
    logout_user()
    flash("Vous avez été déconnecté(e).", category="info")
    session.clear()
    return redirect(url_for("auth_bp.login"))

src/services/dashboard/__init__.py
from .routes import dashboard_bp

__all__ = ("dashboard_bp",)

src/services/dashboard/routes.py
from flask import abort
from flask import Blueprint
from flask import flash
from flask import g
from flask import redirect
from flask import render_template
from flask import url_for
from flask_login import current_user
from flask_login import login_required
from src.services.account import Project
from src.services.account import utils
from src.services.account.forms import ProjectForm

from .func_utils import Hashtags, Comments


dashboard_bp = Blueprint("dashboard_bp", __name__, url_prefix="/panel/~/")


@dashboard_bp.before_request
def dashboard_before_request():
    g.hashtag = Hashtags(current_user)
    g.hashtags_data = g.hashtag.get_hashtag_data()

    g.comment = Comments(current_user)
    g.comments_data = g.comment.get_comments_data()


@dashboard_bp.get("/dashboard/")
@login_required
def dashboard():
    page_title = "Tableau de bord"

    print("hashtags -->", g.hashtags_data)
    print("comments -->", g.comments_data)

    return render_template(
        "dashboard/_base.html",
        user=current_user,
        hashtags=g.hashtags_data,
        page_title=page_title,
    )


@dashboard_bp.get("/project/")
@login_required
def get_projects():
    page_title = "projets"

    # stats_data = ""
    # data = Hashtags(current_user)
    # for item in Project.all(current_user):
    #     stats_data = data.get_statistic(item.name)

    return render_template(
        "project/list.html",
        user=current_user,
        page_title=page_title.capitalize(),
        # stat=stats_data,
    )


@dashboard_bp.get("/result/<string:public_id>")
@login_required
def detail_project(public_id: str):
    project = utils.abort_if_project_doesnt_exist(public_id)

    page_name = project.name
    page_title = "Tag '{0}' data".format(page_name)

    # items_data = g.data.get_detail(page_name)

    return render_template(
        "project/detail.html",
        project=project,
        user=current_user,
        page_title=page_title,
        # item=items_data,
        # stat=g.stats_data,
        # stat_fb=g.stat_fb,
        # stat_insta=g.stat_insta,
    )


@dashboard_bp.get("/result/fb/<string:public_id>")
@login_required
def facebook_detail_project(public_id: str):
    project = utils.abort_if_project_doesnt_exist(public_id)

    page_title = f"Facebook data : '{project.name}!r'"

    # data = Hashtags(current_user)
    # items_data = data.get_detail(project.name)
    # stats_data = data.get_statistic(project.name)

    return render_template(
        "project/fb.html",
        project=project,
        user=current_user,
        page_title=page_title,
        # item=items_data,
        # stat=stats_data,
    )


@dashboard_bp.get("/result/in/<string:public_id>")
@login_required
def instagram_detail_project(public_id: str):
    project = utils.abort_if_project_doesnt_exist(public_id)

    page_title = "Instagram data : '{0}'".format(project.name)

    data = Hashtags(current_user)
    # items_data = data.hashtags_data(project.name)

    return render_template(
        "project/fb.html",
        project=project,
        user=current_user,
        page_title=page_title,
        # item=items_data,
    )


@dashboard_bp.route("/update/<string:public_id>", methods=["GET", "POST"])
@login_required
def update_project(public_id: str):
    page_title = "Mettre à jour les mots-clés/phrases-clés"
    project = utils.abort_if_project_doesnt_exist(public_id)

    if project.user_id != current_user.public_id:
        abort(403)

    form = ProjectForm()
    if form.validate_on_submit():
        keywords = form.name.data.split(",")
        name_data = keywords[0].strip()
        Project.update(project, name_data)
        return redirect(url_for("dashboard_bp.dashboard"))
    return render_template(
        "project/update.html", form=form, page_title=page_title, project=project
    )


@dashboard_bp.get("/delete/<string:public_id>/")
@login_required
def delete_project(public_id: str):
    project = utils.abort_if_project_doesnt_exist(public_id)
    if project.user_id != current_user.public_id:
        abort(403)
    flash(f"{project.name} supprimé avec succès !", "success")
    project.remove()
    return redirect(url_for("dashboard_bp.get_projects"))

src/templates/dashboard/paths/_data.html
<div class="card">
    <div class="card-header border-0 pb-0">
        <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex align-items-center">
                <div>
                    <div class="nav nav-divider">
                        <h6 class="nav-item card-title mb-0">
                            {{ item.owner_username|default('Yimba', true) }}
                        </h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body">
        <p>{{ item.text|truncate(225, True) }}</p>
        <ul class="nav nav-pills nav-pills-light nav-fill nav-stack small border-top border-bottom py-1 my-3">
            <li class="nav-item">
                <span class="nav-link">
                    <i class="align-middle me-1" data-feather="calendar"></i>
                    Publié le {{ item.created_time }}
                </span>
            </li>

            <li class="nav-item">
                <span class="nav-link">
                    <i class="align-middle me-1" data-feather="heart"></i>
                    Likes ({{ item.reactions_total_count|default('0', true) }})
                </span>
            </li>

            <li class="nav-item">
                <span class="nav-link">
                    <i class="align-middle me-1" data-feather="repeat"></i>
                    Commentaires ({{ item.comments_count|default('0', true) }})
                </span>
            </li>

            <li class="nav-item">
                <span class="nav-link">
                    <i class="align-middle me-1" data-feather="share-2"></i>
                    Partages ({{ item.shares_count|default('0', true) }})
                </span>
            </li>
        </ul>
    </div>
</div>

src/templates/dashboard/paths/_header.html
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle js-sidebar-toggle">
        <i class="hamburger align-self-center"></i>
    </a>

    <form class="d-none d-sm-inline-block">
        <div class="input-group input-group-navbar">
            <input type="text" class="form-control shadow-none" placeholder="Rechercher ... " aria-label="Rechercher">
            <button class="btn" type="button">
                <i class="align-middle" data-feather="search"></i>
            </button>
        </div>
    </form>

    <div class="navbar-collapse collapse">
        <ul class="navbar-nav navbar-align">
            <li class="nav-item dropdown">
                <a class="nav-icon pe-md-0 dropdown-toggle" href="#" data-bs-toggle="dropdown">
                    <img class="avatar img-fluid rounded" src="{{ url_for('static', filename='img/avatar.jpg') }}" alt="{{ user }}"/>
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <a class='dropdown-item' href='#!l'><i class="align-middle me-1" data-feather="user"></i>Profile</a>
                    <div class="dropdown-divider"></div>
                    <a href="#!" class="dropdown-item">
                        <i class="align-middle me-1" data-feather="settings"></i>
                        Paramètre du compte
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ url_for('auth_bp.logout') }}" class="dropdown-item">
                        Logout
                    </a>
                </div>
            </li>
        </ul>
    </div>
</nav>

src/templates/dashboard/paths/_kpi.html
<div class="col-sm-4 col-xl-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col mt-0">
                    <h5 class="card-title">Likes</h5>
                </div>

                <div class="col-auto">
                    <div class="stat text-primary">
                        <i class="align-middle" data-feather="heart"></i>
                    </div>
                </div>
            </div>
            <h1 class="mt-1 mb-3">{{ stat[0] }}</h1>
        </div>
    </div>
</div>

<div class="col-sm-4 col-xl-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col mt-0">
                    <h5 class="card-title">Commentaires</h5>
                </div>

                <div class="col-auto">
                    <div class="stat text-primary">
                        <i class="align-middle" data-feather="repeat"></i>
                    </div>
                </div>
            </div>
            <h1 class="mt-1 mb-3">{{ stat[1] }}</h1>
        </div>
    </div>
</div>

<div class="col-sm-4 col-xl-4">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col mt-0">
                    <h5 class="card-title">Partages</h5>
                </div>

                <div class="col-auto">
                    <div class="stat text-primary">
                        <i class="align-middle" data-feather="share-2"></i>
                    </div>
                </div>
            </div>
            <h1 class="mt-1 mb-3">{{ stat[2] }}</h1>
        </div>
    </div>
</div>

src/templates/dashboard/paths/_leftbar.html
<div class="card flex-fill">
	<div class="card-body">
		<h3>Facebook data</h3>
		<div class="d-flex mb-3">
			<div class="flex-grow-1">
				<strong><i class="align-middle me-1 mb-1" data-feather="heart"></i> Likes</strong>
				<h2 class="text-muted">{{ stat_fb[0] }}</h2>
			</div>
		</div>

		<div class="d-flex mb-3">
			<div class="flex-grow-1">
				<strong><i class="align-middle me-1 mb-1" data-feather="repeat"></i> Commentaires</strong>
				<h2 class="text-muted">{{ stat_fb[1] }}</h2>
			</div>
		</div>

		<div class="d-flex mb-3">
			<div class="flex-grow-1">
				<strong><i class="align-middle me-1 mb-1" data-feather="share-2"></i> Partages</strong>
				<h2 class="text-muted">{{ stat_fb[2] }}</h2>
			</div>
		</div>
	</div>
</div>

<div class="card flex-fill">
	<div class="card-body">
		<h3>Instagram data</h3>

		<div class="d-flex mb-3">
			<div class="flex-grow-1">
				<strong><i class="align-middle me-1 mb-1" data-feather="heart"></i> Likes</strong>
				<h2 class="text-muted">{{ stat_insta[0] }}</h2>
			</div>
		</div>

		<div class="d-flex mb-3">
			<div class="flex-grow-1">
				<strong><i class="align-middle me-1 mb-1" data-feather="repeat"></i> Commentaires</strong>
				<h2 class="text-muted">{{ stat_insta[1] }}</h2>
			</div>
		</div>

		<div class="d-flex mb-3">
			<div class="flex-grow-1">
				<strong><i class="align-middle me-1 mb-1" data-feather="share-2"></i> Partages</strong>
				<h2 class="text-muted">{{ stat_insta[2] }}</h2>
			</div>
		</div>
	</div>
</div>

src/templates/dashboard/paths/_sidebar.html
<nav id="sidebar" class="sidebar js-sidebar">
    <div class="sidebar-content js-simplebar">
        <a class='sidebar-brand' href='{{ url_for('dashboard_bp.dashboard') }}'>
            <span class="sidebar-brand-text align-middle">
                {{ config.SITE_NAME }}
            </span>
            <svg class="sidebar-brand-icon align-middle" width="32px" height="32px" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="1.5"
                stroke-linecap="square" stroke-linejoin="miter" color="#FFFFFF" style="margin-left: -3px">
                <path d="M12 4L20 8.00004L12 12L4 8.00004L12 4Z"></path>
                <path d="M20 12L12 16L4 12"></path>
                <path d="M20 16L12 20L4 16"></path>
            </svg>
        </a>

        <ul class="sidebar-nav">
            <li class="sidebar-item active">
                <a href="{{ url_for('dashboard_bp.dashboard') }}" class="sidebar-link">
                    <i class="align-middle" data-feather="sliders"></i>
                    <span class="align-middle">Dashboard</span>
                </a>
            </li>

            <li class="sidebar-item">
                <div class="sidebar-link">
                    <i class="align-middle" data-feather="layout"></i>
                    <span class="align-middle">Projets</span>
                    <a href="{{ url_for('project_bp.create_project') }}">
                        <span class="sidebar-badge badge bg-primary">+</span>
                    </a>
                </div>
            </li>

            <li class="sidebar-item">
                <a data-bs-target="#tags" data-bs-toggle="collapse" class="sidebar-link collapsed">
                    <i class="align-middle" data-feather="check-circle"></i>
                    <span class="align-middle">Tags</span>
                </a>
                <ul id="tags" class="sidebar-dropdown list-unstyled collapse " data-bs-parent="#sidebar">
                    {% for project in user.user_project %}
                        <li class="sidebar-item">
                            <a class='sidebar-link' href='{{ url_for('dashboard_bp.detail_project', public_id=project.public_id) }}'>{{ project.name | capitalize() }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    </div>
</nav>